spring.application.name=MiniPay

spring.datasource.url=jdbc:postgresql://localhost:15432/minipay
spring.datasource.username=minipay
spring.datasource.password=minipay

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.error.include-message=always

minipay.security.username=minipay
minipay.security.password=minipay

minipay.rate-limit.enabled=false
minipay.rate-limit.transfer.limit=5
minipay.rate-limit.transfer.window-seconds=60

minipay.events.kafka.enabled=false
minipay.events.kafka.consumer.enabled=false
minipay.events.kafka.topic=payment-events

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=minipay-api
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.minipay.dto
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
